### ISSUE TITLE
혹시 사용법 간단하게 알 수 있을까요???

### ISSUE THREAD

**Issue by somebody1503** [Sylvia3259/classcard-hack#1]
ㅠㅠ somebody1718@gmail.com

**Comment by Sylvia3259** [comment]
답변이 늦어 죄송합니다. 깃헙에 이런 기능이 있는지도 몰랐네요 ㅋㅋ
https://youtu.be/R23t16_-vEk
위 영상 참고하시면 될 거 같습니다!

**Comment by somebody1503** [comment]
저도 이런기능있는걸 첨알았네요 ㅋㅋㅋ 감사합니다!!!!

**Comment by kju911** [comment]
감사합니다 사용법 찾다가 드디어 확인했네요
